Updated Docs And Removed Customer Folder
emumba-msft-data-pipelines/jll-one-click-deployments pull request #10
Opened 2021-04-02 11:52 UTC by osamaemumba

Kindly verify that:
1- Except for UsaFacts dataset, the customer folder for all other datasets is deleted.
2- The documentation for **all datasets** is updated:

- Updated table of contents with 'Key Vault Secrets And Access Policies' at 4.
- Parameters list includes key vault name and Azure User Object Id.
- Section 'Key Vault Secrets And Access Policies' (with sub-sections Getting the User Object Id, Add Access Policy and Update Secret Values) is added with all the screenshots.
- All the screenshots appear for the older sections as well.

2021-04-02 12:07 UTC, insidero commented on datasets/jll/USAFacts-data/public/Readme.md
> +   - SQL Server Administrator Password
Password has been remvoed

2021-04-02 12:09 UTC, osamaemumba commented on datasets/jll/USAFacts-data/public/Readme.md
> +   - SQL Server Administrator Password
good point

2021-04-02 12:11 UTC, osamaemumba commented on datasets/jll/USAFacts-data/public/Readme.md
> +   - SQL Server Administrator Password
i have removed the password

2021-04-04 09:42 UTC, insidero commented on datasets/jll/USAFacts-data/public/Readme.md
> +Azure Key Vault is a cloud service for securely storing and accessing secrets. A secret is anything that you want to tightly control access to, such as API keys, passwords, certificates, or cryptogra
**Correction:** Here, two secrets are being saved in the key vault with access given to the data factory and to the user whose object id will be provided while creating the deployment

2021-04-04 09:43 UTC, insidero commented on datasets/jll/USAFacts-data/public/Readme.md
> +The user whose object id will be provided is given full access to all secrets, keys and certificates inside the key vault. While the data factory is given GET access to any secret in the key vault.
**Correction**
While the data factory  has the GET access to the secrets in the key vault.

2021-04-04 09:43 UTC, insidero commented on datasets/jll/USAFacts-data/public/Readme.md
> +1. Type Users in the search bar inside azure portal. Click Users.
Users should be bold or higlighted

2021-04-04 09:47 UTC, insidero requested changes
Kindly make the text bold/italic where it signifies an option or a UI element.

2021-04-06 08:20 UTC, merged